### ISSUE TITLE
Null pointer redirection is not checked

### ISSUE THREAD

**Issue by Yanok35** [cogip/RIOT#3]
https://github.com/cogip/RIOT/blob/5f7cbdb13004276c3865ae4299719ce7fd28eae6/cpu/stm32_common/periph/qdec.c#L112-L117

Please consider protecting the selected line from being executed "if (cb)" is NULL

**Comment by gdoffe** [comment]
Solved mainline with https://github.com/RIOT-OS/RIOT/pull/14125

**Comment by gdoffe** [comment]
Merged upstream: https://github.com/RIOT-OS/RIOT/commit/892370121ded21733f2a10b35563646f2472cc74
